CREATE TABLE "even_expense" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "even_expense_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" varchar(256) NOT NULL,
	"amount" numeric(10, 2) NOT NULL,
	"currency" varchar(3) DEFAULT 'USD' NOT NULL,
	"category" varchar(100),
	"description" text,
	"date" date NOT NULL,
	"userId" varchar(256) NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "even_friendship" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "even_friendship_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" varchar(256) NOT NULL,
	"friendUserId" varchar(256) NOT NULL,
	"status" varchar(20) DEFAULT 'pending' NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "even_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "even_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE INDEX "user_idx" ON "even_expense" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "date_idx" ON "even_expense" USING btree ("date");--> statement-breakpoint
CREATE INDEX "category_idx" ON "even_expense" USING btree ("category");--> statement-breakpoint
CREATE INDEX "user_friend_idx" ON "even_friendship" USING btree ("userId","friendUserId");--> statement-breakpoint
CREATE INDEX "friend_user_idx" ON "even_friendship" USING btree ("friendUserId","userId");--> statement-breakpoint
CREATE INDEX "status_idx" ON "even_friendship" USING btree ("status");--> statement-breakpoint
CREATE INDEX "name_idx" ON "even_post" USING btree ("name");