CREATE TABLE "even_group_invitation" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "even_group_invitation_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"groupId" integer NOT NULL,
	"invitedUserId" varchar(256) NOT NULL,
	"invitedByUserId" varchar(256) NOT NULL,
	"status" varchar(20) DEFAULT 'pending' NOT NULL,
	"message" text,
	"expiresAt" timestamp with time zone,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"respondedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE INDEX "group_invite_idx" ON "even_group_invitation" USING btree ("groupId","invitedUserId");--> statement-breakpoint
CREATE INDEX "invited_user_idx" ON "even_group_invitation" USING btree ("invitedUserId");--> statement-breakpoint
CREATE INDEX "inviter_idx" ON "even_group_invitation" USING btree ("invitedByUserId");--> statement-breakpoint
CREATE INDEX "invite_status_idx" ON "even_group_invitation" USING btree ("status");