CREATE TABLE "even_expense_payment" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "even_expense_payment_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"expenseId" integer NOT NULL,
	"userId" varchar(256) NOT NULL,
	"amount" numeric(10, 2) NOT NULL,
	"percentage" numeric(5, 2),
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
DROP INDEX "paid_by_idx";--> statement-breakpoint
ALTER TABLE "even_expense" ADD COLUMN "paymentMode" varchar(20) DEFAULT 'single' NOT NULL;--> statement-breakpoint
CREATE INDEX "expense_payment_idx" ON "even_expense_payment" USING btree ("expenseId","userId");--> statement-breakpoint
CREATE INDEX "payment_expense_idx" ON "even_expense_payment" USING btree ("expenseId");--> statement-breakpoint
CREATE INDEX "payment_user_idx" ON "even_expense_payment" USING btree ("userId");--> statement-breakpoint
ALTER TABLE "even_expense" DROP COLUMN "paidBy";