CREATE TABLE "even_expense_comment" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "even_expense_comment_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"expenseId" integer NOT NULL,
	"userId" varchar(256) NOT NULL,
	"comment" text NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "even_expense_history" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "even_expense_history_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"expenseId" integer NOT NULL,
	"editedBy" varchar(256) NOT NULL,
	"changeType" varchar(50) NOT NULL,
	"changes" json,
	"editReason" text,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE INDEX "expense_comment_idx" ON "even_expense_comment" USING btree ("expenseId");--> statement-breakpoint
CREATE INDEX "comment_user_idx" ON "even_expense_comment" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "expense_history_idx" ON "even_expense_history" USING btree ("expenseId");--> statement-breakpoint
CREATE INDEX "edited_by_idx" ON "even_expense_history" USING btree ("editedBy");--> statement-breakpoint
CREATE INDEX "change_type_idx" ON "even_expense_history" USING btree ("changeType");